### ISSUE TITLE
Rule closing does not take effect

### ISSUE THREAD

**Issue by Summary-wcj** [apache/shenyu#4513] opened 2023-03-29 09:41 UTC
### Question

When the selector rule is closed and the interface is requested, the closed selector rule will still be matched
![image](https://user-images.githubusercontent.com/34983781/228493691-2873635c-40ff-4a2e-a4c9-26c3c6f93f3d.png)
![image](https://user-images.githubusercontent.com/34983781/228493828-899b5a4d-bcca-4070-8181-bce4b579b3b0.png)
![image](https://user-images.githubusercontent.com/34983781/228493964-5cfc5434-ed64-4f99-8d6f-b14a8af041c0.png)

**Comment by yu199195** [comment] 2023-03-29 10:14
you used which data sync？  whats version？

**Comment by Summary-wcj** [comment] 2023-03-29 11:30
> you used which data sync？ whats version？
I pulled the master branch code and started the test locally

**Comment by moremind** [comment] 2023-03-29 13:16
I have confirmed this bug, because shenyu uses the two-level cache, but shenyu trie not close rule data. Thanks for your response, I will fix it in a few time.

**Comment by yu199195** [comment] 2023-03-30 03:07
good @moremind

**Comment by moremind** [comment] 2023-03-30 13:58
It has fixed in https://github.com/apache/shenyu/pull/4515, please use shenyu 2.6.0, thanks for your response!

**Closed** 2023-03-31 03:06 UTC
Labels: type: question

**Comment by Summary-wcj** [comment] 2023-03-31 05:02
Thumb up for you
